DROP TABLE IF EXISTS msg;
DROP TABLE IF EXISTS sms;

CREATE TABLE sms (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  sender_number TEXT NOT NULL,
  receiver_number TEXT NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  body TEXT NOT NULL
);